/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openZeppelin from "./OpenZeppelin";
export type { openZeppelin };
import type * as multicall from "./multicall";
export type { multicall };
export type { IwULX } from "./IwULX";
export type { MasterChef } from "./MasterChef";
export type { Migrations } from "./Migrations";
